# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
