# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mywiki', '0002_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
