# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywiki', '0003_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='period',
            field=models.DateField(null=True),
        ),
    ]
