# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywiki', '0003_auto_20171012_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='revision',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mywiki.ip'),
        ),
    ]
